// -------------------------------------------------------------------------------------------
// <copyright file="BaseParameter.cs" company="MapWindow OSS Team - www.mapwindow.org">
//  MapWindow OSS Team - 2015
// </copyright>
// -------------------------------------------------------------------------------------------

using System;
using System.Reflection;
using MW5.Plugins.Interfaces;
using MW5.Tools.Controls.Parameters;
using MW5.Tools.Services;

namespace MW5.Tools.Model.Parameters
{
    /// <summary>
    /// The base parameter.
    /// </summary>
    public abstract class BaseParameter
    {
        public BaseParameter()
        {
            HasDatasource = false;
        }

        /// <summary>
        /// Gets or sets the control.
        /// </summary>
        public ParameterControlBase Control { get; set; }

        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the display name.
        /// </summary>
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the index.
        /// </summary>
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="BaseParameter"/> is required.
        /// </summary>
        public bool Required { get; set; }

        public object DefaultValue { get; set; }

        public PropertyInfo ToolProperty { get; set; }

        public IGisTool Tool { get; set; }

        public virtual bool HasDatasource { get; private set; }

        /// <summary>
        /// Gets or sets value restored from config from previous run of the tool.
        /// </summary>
        public object PreviousValue { get; set; }

        /// <summary>
        /// Gets the initial value of the control. It's either DefaultValue or PreviousValue.
        /// </summary>
        public object InitialValue
        {
            get
            {
                if (PreviousValue != null)
                {
                    return PreviousValue;
                }

                return DefaultValue;
            }
        }

        /// <summary>
        /// Gets the value of the parameter. It's value set in the control if control is attached, or 
        /// the value of the relevant property of the tool class otherwise.
        /// </summary>
        public virtual object Value
        {
            get
            {
                if (Control != null)
                {
                    return Control.GetValue();
                }

                // use tool property directly if there is no control associated with parameter
                // in such manner we can still use parameters for validation
                // if even if standard autogenerated UI isn't used
                return ToolProperty.GetValue(Tool);
            }
        }

        /// <summary>
        /// Gets a value indicating whether the parameter should be serialized into config file 
        /// to preserve the last used value.
        /// </summary>
        public virtual bool Serializable
        {
            get { return false; }
        }

        public override string ToString()
        {
            var val = Value;
            var s = val != null ? val.ToString() : string.Empty;
            return string.Format("{0}: {1}", DisplayName, s);
        }
    }
}